### ISSUE TITLE
Consider switching to `predicates` crate for predicates

### ISSUE THREAD

**Issue by teohhanhui** [greyblake/nutype#129]
You can see it's already wildly popular: https://crates.io/crates/predicates

It'd unlock combinatorial logic on predicates.

Existing custom predicate functions can be wrapped like this: https://docs.rs/predicates/latest/predicates/function/fn.function.html

**Comment by greyblake** [comment]
@teohhanhui 

Hi it's first time I hear of `predicates` crate, it looks interesting, so thanks for bringing this!

While there is some overlap between `predicates` and the validation rules in nutype, it cannot be fully replaced.
Predicates return `bool`, without providing information what exactly caused the failure.
