### ISSUE TITLE
Add support to UUID

### ISSUE THREAD

**Issue by ronanM** [greyblake/nutype#165]
`UUID` fields are often used in data/DB design.

**Comment by greyblake** [comment]
fI you need UUID, you should use [uuid](https://crates.io/crates/uuid) crate and proper `uuid::Uuid` type instead of trying to fake uuid with `struct Uuid(String)` or something similar.

If I misunderstood your request please reopen and elaborate more on it.

**Comment by ronanM** [comment]
Ok, Nutype can't offer benefits over `struct MyUuid(uuid)` ?

**Comment by greyblake** [comment]
@ronanM Could you please give some examples of what kind of benefits would you expect?
