### ISSUE TITLE
validate with error with module path fails

### ISSUE THREAD

**Issue by vic1707** [greyblake/nutype#186]
I don't know if the issue name is right or understandable sorry.

I found out that 
```rs
#[nutype(validate(with = fs::exists, error = io::Error))]
struct File(PathBuf);
```
causes an error at the `io::`.
I think the macro should support that.

### Current workaround

`use std::io::Error as IoError;` 🤷

**Comment by greyblake** [comment]
Good catch! Thanks for reporting! I will fix that.

Though, I'd like to point, that the example above is not gonna work anyway because the function passed to `with = ` should return `Result<(), Error>`.
In case of  `fs::exists` it returns `Result<bool, Error>`.

**Comment by vic1707** [comment]
Yup I got that too, I made a separate function to check if it exists and is a file 🙃
When opening the issue I reverted to that state and forgot to check if it compiled since I was interested by the macro parsing 🤣
That's my bad

**Comment by greyblake** [comment]
Fixed in https://github.com/greyblake/nutype/pull/187
