### ISSUE TITLE
Opt-in for `new_unchecked`

### ISSUE THREAD

**Issue by tyranron** [greyblake/nutype#2]
First, thanks for such a nice crate!

## Feature request

We do use the very similar approach in our codebases, and this crate may strip a lot of boilerplate in our projects. However, it lacks one feature we do often use: generating `unsafe pub fn new_unchecked() -> Self`. It would be nice to be able to opt-in for it via some attribute argument, like: `#[nutype(unchecked)]` for example.

## Motivation

There are 2 main situations where we use `new_unchecked()` in our codebases. Both are related to the situations where `validation` represents quite a heavy operation:
1. Reading a value from database in `FromSql` implementation, where the type invariants are guaranteed by database constraints, thus no need to perform heavy validation.
2. `From` conversion between the same types declared on different layers (like GraphQL API layer <-> domain layer), thus no need to perform the validation again once it's already guaranteed by another type.

**Comment by greyblake** [comment]
@tyranron Hi, thanks for bringing this.
I knew this will be requested... it was just question of time :)

I do understand that for some apps, that strike for maximum performance it's indeed, but I would like to emphasize that this practice is not encouraged.

I guess it would put it behind the crates feature and make it disabled by default.
If the feature is explicitly enabled, it will be possible to do, something like:


```rust
#[nutype(
    sanitize(trim, lowercase)
    validate(present, with = |s| s.contains('@'))
    new_unchecked
)]
pub struct Email(String)
```

this would result into:

```rust
impl Email {
    pub fn new_unchecked(value: String) -> Email {
        Email(value)
    }
}
```
Notice the absence of conversion, `new_unchecked` receives `String`, not `impl Into<String>`.


What do you think?

**Comment by tyranron** [comment]
@greyblake 

> I guess it would put it behind the crates feature and make it disabled by default.

I'm totally okay with that.

> Notice the absence of conversion, `new_unchecked` receives `String`, not `impl Into<String>`.

This is also OK. It's not something we do that often, and better not encourage use it with improved ergonomics.

> this would result into:
>
> ```rust
> impl Email {
>     pub fn new_unchecked(value: String) -> Email {
>         Email(value)
>    }
> }
> ```

Hmm... I tend to have it like:
```patch
impl Email {
-   pub fn new_unchecked(value: String) -> Email {
+   pub unsafe fn new_unchecked(value: String) -> Email {
        Email(value)
    }
}
```
The `unsafe` signature is important here, because the caller is obligated to guarantee type invariants by himself. Violating them may potentially lead to memory unsafety as well (as we have with `NonZero*` types in `std`), especially when we'll get type niches stabilized.

**Comment by greyblake** [comment]
Addressed in https://github.com/greyblake/nutype/pull/16
