### ISSUE TITLE
Feature request: enable setting custom default values

### ISSUE THREAD

**Issue by pflakus** [greyblake/nutype#36]
# Currently

`nutype` enables users to derive several [derivable traits](https://docs.rs/nutype/0.2.0/nutype/#string-derivable-traits). However deriving `Default` yields an error (`unsupported trait derive: Default`).

# Feature Request

- enable `nutype`s to handle/derive the `Default` trait as expected.  
- implement another annotation (alongside `validate` and `sanitize`) like `default = `, which enables users to specify a default value and/or the name of a function that yields the default value.

# Workaround

It is possible to manually implement the `Default` trait on a `nutype` struct.  
This is functionally sufficient. Just not quite elegant, compared to what `nutype`s annotations might enable us to do. :)

# Considerations/constraints

The thing to keep in mind is that the default value should not be able to violate the promises of the `nutype` validation. So presumably we need to be ensured this at compile time.  
I can't estimate how difficult a constraint that is to implement. But I thought I'd mention it immediately.

**Comment by greyblake** [comment]
@pflakus Hi, thanks for the request. I think having things would be helpful for many other users.

Let's start with the syntax.  Do I get it right that  the desired syntax would look like the following:

```rs
#[nutype(
    validate(min = 0.0, max = 100.0)
    default = 50.0
)]
#[derive(Default)]
pub struct Percent(f64);
```
? 

* Deriving `Default` without `default = ` should result into a compile error
* Setting `default = ` without `derive(Default)` should also lead to a compile error

> The thing to keep in mind is that the default value should not be able to violate the promises of the nutype validation.

This is indeed very important.
Unfortunately it won't be able to do always. 

Consider the example above, defined as 

```rs
#[nutype(
    validate(with = |n| n >= 0.0 && n <= 100.0)
    default = 50.0
)]
#[derive(Default)]
pub struct Percent(f64);
```

Note, that there is a custom validator function (in this case closure) defined with `with =`.
Unfortunately , proc macros in Rust a not powerful enough to lookup and execute the provided custom function at compile time.
It means, that ensuring that the promises of nutype is not violated is not possible at compile time.

However, it can be worked around a unit test.
In theory the macro can generate a tiny unit test, that ensures that the default value is indeed matching all the necessary criteria.

What do you think?

**Comment by pflakus** [comment]
Seconded the whole comment, no notes. 😉

The idea with the injected unit test is pretty nifty!  
Imho your approach, in combination with documentation having a prominent explanation making it clear how this feature is intended to be used, sounds like a decent compromise to ensure that people can use it safely.

**Comment by greyblake** [comment]
Addressed in https://github.com/greyblake/nutype/pull/39
