### ISSUE TITLE
Move derive into nutype attributes

### ISSUE THREAD

**Issue by greyblake** [greyblake/nutype#69]
## Context

At the moment it's possible to derive traits by using the regular `#[derive]` macro. For example:
```rs
#[nutype(validate(not_empty))]
#[derive(Debug)]
pub struct Name(String);
```

The initial idea behind this was to give a "natural" syntax/feeling to Rust developers.
In reality however, `nutype` fully controls `#[derive()]`: it parses it, and generates code. It's not done by the standard `derive` macro.

Note also that the following will not compile:
```rs
#[derive(Debug)]
#[nutype(validate(not_empty))]
pub struct Name(String);
```

Because in this case, `nutype` has no notion about `derive` and the standard `derive` macro is applied on tuple struct with private inner value, which cannot be access directly.
However, people got confused sometimes, thinking that the 2 snippets above are equal. 

## Motivation

To eliminate confusion and make it clear  for the library users,  we want to move `derive` macro into set of `nutype` attributes, e.g.:
```rs
#[nutype(
    validate(not_empty),
    derive(Debug)
)]
pub struct Name(String);
```

## Spec

* Add a new field to `ParseableAttributes` : `derive_traits: Vec<SpannedItem<DeriveTrait>>`,
* Update `impl Parse for ParseableAttributes` to parse `derive` into `derive_traits`, for inspiration take the current implementation in `fn parse_ident_into_derive_trait`
* Adjust the tests (to run all possible tests run `make test`)
* When `#[derive(...)]` is used outside of `#[nutype(...)]` return a compilation error, explaining how to use derive correctly. Add a compiletests to test the error message.
* Update CHANGELOG.md with the information about the breaking change. Do not update README (will do it before the release).

## Acceptance Criteria

1. The following code should compile and `Name` should have `Debug` implemented:

```rs
#[nutype(
    validate(not_empty),
    derive(Debug)
)]
pub struct Name(String)
```

2. The following code should result into an error message with an example how to use `derive(..)` properly:

```rs
#[nutype(
    validate(not_empty)
)]
#[derive(Debug)]
pub struct Name(String)
```

**Comment by Narayanbhat166** [comment]
I have a similar issue. I want to add a attribute type proc macro to my new type. Is this even supported? or is there any workaround for this?

```rust
#[nutype::nutype(
    validate(greater_or_equal = MIN_ORDER_FULFILLMENT_EXPIRY, less_or_equal = MAX_ORDER_FULFILLMENT_EXPIRY),
    derive(Clone, Copy, Debug, AsRef, Deserialize, Serialize)
)]
#[diesel(sql_type = diesel::sql_types::Text)]
pub struct OrderFulfillmentTime(i64);
```

The error that I get is
```text
#[nutype] does not support this attribute.
```

**Comment by greyblake** [comment]
@Narayanbhat166 
Hi, the syntax you're trying is not supported.
I consider adding adding support for diesel and sqlx in the future.

At the moment the only work around possible is to implement all the traits you need yourself based on the existing traits and `::try_new()` constructor.
